# Generated by Django 4.2.7 on 2023-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='Valor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='PCs/'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='Valor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='PCs/'),
        ),
    ]
