# Generated by Django 4.2.7 on 2023-11-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCs', '0003_alter_desktop_valor_alter_monitor_valor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
